import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Loader2, LogOut, Search, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { staffSupabase } from "@/integrations/supabase/staff-client";
import { Input } from "@/components/ui/input";

export const Route = createFileRoute("/staff/lolos")({
  head: () => ({ meta: [{ title: "Peserta Lolos Essay — Safar Iman" }] }), component: StaffPassedPage,
});
type Row={id:string;registration_code:string;full_name:string;email:string;whatsapp:string;city:string;status:string;staff_review:{reviewer_name:string;updated_at:string}|null};
function StaffPassedPage(){
  const navigate=useNavigate();const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[q,setQ]=useState("");
  useEffect(()=>{void(async()=>{const{data:{session}}=await staffSupabase.auth.getSession();if(!session){navigate({to:"/staff/login"});return;}const{data,error}=await staffSupabase.functions.invoke("staff-essay",{body:{action:"list"}});if(error){toast.error("Akses staff tidak aktif");navigate({to:"/staff/login"});return;}setRows((data?.participants??[]).filter((r:Row)=>r.status==="interview"));setLoading(false);})();},[]);
  const filtered=useMemo(()=>rows.filter(r=>!q.trim()||[r.full_name,r.registration_code,r.email,r.city,r.staff_review?.reviewer_name].some(v=>v?.toLowerCase().includes(q.toLowerCase()))),[rows,q]);
  const logout=async()=>{await staffSupabase.auth.signOut();navigate({to:"/staff/login"});};
  if(loading)return <div className="min-h-screen grid place-items-center"><Loader2 className="animate-spin text-accent"/></div>;
  return <div className="min-h-screen bg-secondary/30"><header className="bg-card border-b"><div className="max-w-7xl mx-auto min-h-16 px-4 py-2 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><ShieldCheck className="text-accent"/><div><b>Dashboard Staff Seleksi</b><div className="text-[10px] text-muted-foreground">Daftar internal peserta lolos</div></div></div><nav className="flex items-center gap-2"><Link to="/staff" className="rounded-lg border px-3 py-2 text-xs font-semibold">Sudah Mengirim</Link><Link to="/staff/lolos" className="rounded-lg bg-accent text-white px-3 py-2 text-xs font-semibold">Peserta Lolos</Link><button onClick={logout} className="flex items-center gap-1 text-sm ml-1"><LogOut className="size-4"/>Keluar</button></nav></div></header><main className="max-w-7xl mx-auto p-4 sm:p-6 space-y-5"><div className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">Daftar ini masih bersifat internal. Staff tidak dapat mempublikasikannya; toggle publish tetap di dashboard admin.</div><div className="grid sm:grid-cols-[220px,1fr] gap-4"><div className="rounded-2xl bg-emerald text-white p-5"><CheckCircle2/><div className="text-3xl font-bold mt-3">{rows.length}</div><div className="text-sm">Peserta Lolos</div></div><div className="bg-card border rounded-2xl p-4"><div className="relative"><Search className="absolute size-4 left-3 top-3 text-muted-foreground"/><Input className="pl-9" placeholder="Cari peserta atau staff pengoreksi" value={q} onChange={e=>setQ(e.target.value)}/></div></div></div><div className="bg-card border rounded-2xl overflow-x-auto"><table className="w-full text-sm"><thead className="bg-secondary/60"><tr><th className="text-left p-3">Peserta</th><th className="text-left p-3">Kontak</th><th className="text-left p-3">Kota</th><th className="text-left p-3">Staff Pengoreksi</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t"><td className="p-3"><b>{r.full_name}</b><div className="font-mono text-xs text-muted-foreground">{r.registration_code}</div></td><td className="p-3 text-xs">{r.email}<div>{r.whatsapp}</div></td><td className="p-3">{r.city}</td><td className="p-3"><b>{r.staff_review?.reviewer_name||"—"}</b>{r.staff_review&&<div className="text-xs text-muted-foreground">{new Date(r.staff_review.updated_at).toLocaleString("id-ID")}</div>}</td></tr>)}</tbody></table>{filtered.length===0&&<div className="p-10 text-center text-muted-foreground">Belum ada peserta yang ditetapkan lolos.</div>}</div></main></div>;
}
