import { Loader2, MessageCircle, Minus, Send, Users, X } from "lucide-react";
import { type FormEvent, type KeyboardEvent, useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { staffSupabase } from "@/integrations/supabase/staff-client";

type ChatMessage={id:string;staff_user_id:string;staff_name:string;message:string;created_at:string};
const timeLabel=(value:string)=>new Intl.DateTimeFormat("id-ID",{hour:"2-digit",minute:"2-digit",day:"2-digit",month:"short",timeZone:"Asia/Jakarta"}).format(new Date(value));

export function StaffGroupChat(){
  const [open,setOpen]=useState(false),[messages,setMessages]=useState<ChatMessage[]>([]),[currentUserId,setCurrentUserId]=useState(""),[draft,setDraft]=useState("");
  const [loading,setLoading]=useState(false),[sending,setSending]=useState(false); const scrollRef=useRef<HTMLDivElement>(null);
  const loadMessages=async(silent=false)=>{if(!silent)setLoading(true);const{data,error}=await staffSupabase.functions.invoke("staff-essay",{body:{action:"chat_list"}});if(!silent)setLoading(false);if(error){if(!silent)toast.error("Chat staff belum dapat dimuat");return;}setMessages((data?.messages??[])as ChatMessage[]);setCurrentUserId(String(data?.current_user_id??""));};
  useEffect(()=>{if(window.matchMedia("(min-width: 1280px)").matches)setOpen(true);},[]);
  useEffect(()=>{if(!open)return;void loadMessages();const timer=window.setInterval(()=>void loadMessages(true),7000);return()=>window.clearInterval(timer);},[open]);
  useEffect(()=>{if(open)requestAnimationFrame(()=>{if(scrollRef.current)scrollRef.current.scrollTop=scrollRef.current.scrollHeight;});},[messages,open]);
  const sendMessage=async(event?:FormEvent)=>{event?.preventDefault();const message=draft.trim();if(!message||sending)return;setSending(true);const{data,error}=await staffSupabase.functions.invoke("staff-essay",{body:{action:"chat_send",message}});setSending(false);if(error){toast.error(error.message||"Pesan gagal dikirim");return;}setDraft("");if(data?.message)setMessages(previous=>[...previous.filter(item=>item.id!==data.message.id),data.message as ChatMessage]);};
  const keyDown=(event:KeyboardEvent<HTMLTextAreaElement>)=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void sendMessage();}};
  if(!open)return <button type="button" onClick={()=>setOpen(true)} className="fixed z-40 bottom-5 right-5 rounded-full bg-emerald text-primary-foreground shadow-xl px-4 py-3 inline-flex items-center gap-2 font-bold"><MessageCircle className="size-5"/>Chat Staff</button>;
  return <aside className="fixed z-40 right-3 sm:right-5 top-20 bottom-3 sm:bottom-5 w-[calc(100vw-1.5rem)] sm:w-[360px] rounded-2xl border bg-card shadow-2xl flex flex-col overflow-hidden">
    <header className="bg-gradient-emerald text-primary-foreground px-4 py-3 flex items-center gap-3"><div className="size-9 rounded-full bg-white/15 grid place-items-center"><Users className="size-5"/></div><div className="min-w-0 flex-1"><div className="font-bold">Koordinasi Staff</div><div className="text-[11px] opacity-80">Chat bersama seluruh pengoreksi</div></div><button type="button" onClick={()=>setOpen(false)} className="rounded-full p-2 hover:bg-white/15" aria-label="Tutup chat"><span className="hidden xl:block"><Minus className="size-4"/></span><span className="xl:hidden"><X className="size-4"/></span></button></header>
    <div ref={scrollRef} className="flex-1 overflow-y-auto bg-secondary/30 p-3 space-y-3">{loading?<div className="h-full grid place-items-center"><Loader2 className="size-5 animate-spin text-accent"/></div>:messages.length===0?<div className="h-full grid place-items-center text-center px-8"><div><MessageCircle className="size-9 mx-auto mb-2 text-muted-foreground"/><p className="text-sm font-semibold">Belum ada percakapan</p><p className="text-xs text-muted-foreground">Mulai koordinasi dengan staff lainnya.</p></div></div>:messages.map(item=>{const mine=item.staff_user_id===currentUserId;return <div key={item.id} className={mine?"flex justify-end":"flex justify-start"}><div className={`max-w-[85%] rounded-2xl px-3 py-2 ${mine?"bg-emerald text-primary-foreground rounded-br-md":"bg-card border rounded-bl-md"}`}>{!mine&&<div className="text-[10px] font-bold text-accent mb-0.5">{item.staff_name}</div>}<div className="text-sm whitespace-pre-wrap break-words">{item.message}</div><div className={`mt-1 text-[9px] text-right ${mine?"text-primary-foreground/70":"text-muted-foreground"}`}>{timeLabel(item.created_at)}</div></div></div>;})}</div>
    <form onSubmit={sendMessage} className="border-t bg-card p-3"><div className="flex items-end gap-2"><textarea value={draft} onChange={event=>setDraft(event.target.value)} onKeyDown={keyDown} maxLength={2000} rows={2} placeholder="Tulis pesan koordinasi..." className="min-h-[44px] max-h-28 flex-1 resize-none rounded-xl border bg-background px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"/><button type="submit" disabled={!draft.trim()||sending} className="size-11 shrink-0 rounded-xl bg-accent text-primary-foreground grid place-items-center disabled:opacity-50">{sending?<Loader2 className="size-4 animate-spin"/>:<Send className="size-4"/>}</button></div><div className="mt-1 text-[10px] text-muted-foreground">Enter untuk kirim · Shift+Enter untuk baris baru</div></form>
  </aside>;
}
