/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwibbonRouteImport } from './routes/twibbon'
import { Route as SuksesRouteImport } from './routes/sukses'
import { Route as DaftarMandiriRouteImport } from './routes/daftar-mandiri'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as BerkasRouteImport } from './routes/berkas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiPublicMpwaSplatRouteImport } from './routes/api/public/mpwa.$'

const TwibbonRoute = TwibbonRouteImport.update({
  id: '/twibbon',
  path: '/twibbon',
  getParentRoute: () => rootRouteImport,
} as any)
const SuksesRoute = SuksesRouteImport.update({
  id: '/sukses',
  path: '/sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarMandiriRoute = DaftarMandiriRouteImport.update({
  id: '/daftar-mandiri',
  path: '/daftar-mandiri',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasRoute = BerkasRouteImport.update({
  id: '/berkas',
  path: '/berkas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpwaSplatRoute = ApiPublicMpwaSplatRouteImport.update({
  id: '/api/public/mpwa/$',
  path: '/api/public/mpwa/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/berkas': typeof BerkasRoute
  '/daftar': typeof DaftarRoute
  '/daftar-mandiri': typeof DaftarMandiriRoute
  '/sukses': typeof SuksesRoute
  '/twibbon': typeof TwibbonRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/mpwa/$': typeof ApiPublicMpwaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/berkas': typeof BerkasRoute
  '/daftar': typeof DaftarRoute
  '/daftar-mandiri': typeof DaftarMandiriRoute
  '/sukses': typeof SuksesRoute
  '/twibbon': typeof TwibbonRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/mpwa/$': typeof ApiPublicMpwaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/berkas': typeof BerkasRoute
  '/daftar': typeof DaftarRoute
  '/daftar-mandiri': typeof DaftarMandiriRoute
  '/sukses': typeof SuksesRoute
  '/twibbon': typeof TwibbonRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/mpwa/$': typeof ApiPublicMpwaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/berkas'
    | '/daftar'
    | '/daftar-mandiri'
    | '/sukses'
    | '/twibbon'
    | '/admin/login'
    | '/admin/'
    | '/api/public/mpwa/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/berkas'
    | '/daftar'
    | '/daftar-mandiri'
    | '/sukses'
    | '/twibbon'
    | '/admin/login'
    | '/admin'
    | '/api/public/mpwa/$'
  id:
    | '__root__'
    | '/'
    | '/berkas'
    | '/daftar'
    | '/daftar-mandiri'
    | '/sukses'
    | '/twibbon'
    | '/admin/login'
    | '/admin/'
    | '/api/public/mpwa/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BerkasRoute: typeof BerkasRoute
  DaftarRoute: typeof DaftarRoute
  DaftarMandiriRoute: typeof DaftarMandiriRoute
  SuksesRoute: typeof SuksesRoute
  TwibbonRoute: typeof TwibbonRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicMpwaSplatRoute: typeof ApiPublicMpwaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/twibbon': {
      id: '/twibbon'
      path: '/twibbon'
      fullPath: '/twibbon'
      preLoaderRoute: typeof TwibbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sukses': {
      id: '/sukses'
      path: '/sukses'
      fullPath: '/sukses'
      preLoaderRoute: typeof SuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-mandiri': {
      id: '/daftar-mandiri'
      path: '/daftar-mandiri'
      fullPath: '/daftar-mandiri'
      preLoaderRoute: typeof DaftarMandiriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas': {
      id: '/berkas'
      path: '/berkas'
      fullPath: '/berkas'
      preLoaderRoute: typeof BerkasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mpwa/$': {
      id: '/api/public/mpwa/$'
      path: '/api/public/mpwa/$'
      fullPath: '/api/public/mpwa/$'
      preLoaderRoute: typeof ApiPublicMpwaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BerkasRoute: BerkasRoute,
  DaftarRoute: DaftarRoute,
  DaftarMandiriRoute: DaftarMandiriRoute,
  SuksesRoute: SuksesRoute,
  TwibbonRoute: TwibbonRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicMpwaSplatRoute: ApiPublicMpwaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
