/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TwibbonRouteImport } from './routes/twibbon'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SuksesRouteImport } from './routes/sukses'
import { Route as PendaftaranSuksesRouteImport } from './routes/pendaftaran-sukses'
import { Route as PendaftaranRouteImport } from './routes/pendaftaran'
import { Route as EssayRouteImport } from './routes/essay'
import { Route as DonasiRouteImport } from './routes/donasi'
import { Route as DaftarMandiriRouteImport } from './routes/daftar-mandiri'
import { Route as DaftarGelombang2RouteImport } from './routes/daftar-gelombang-2'
import { Route as DaftarGelombang1RouteImport } from './routes/daftar-gelombang-1'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as BerkasRouteImport } from './routes/berkas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWaSetupRouteImport } from './routes/admin.wa-setup'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPesertaIndexRouteImport } from './routes/admin.peserta.index'
import { Route as AdminPengaturanIndexRouteImport } from './routes/admin.pengaturan.index'
import { Route as AdminPesertaSelfFundedRouteImport } from './routes/admin.peserta.self-funded'
import { Route as AdminPesertaRegulerRouteImport } from './routes/admin.peserta.reguler'
import { Route as AdminPengaturanTwibbonRouteImport } from './routes/admin.pengaturan.twibbon'
import { Route as AdminPengaturanPanduanRouteImport } from './routes/admin.pengaturan.panduan'
import { Route as AdminPengaturanGelombangRouteImport } from './routes/admin.pengaturan.gelombang'
import { Route as AdminPengaturanDonasiRouteImport } from './routes/admin.pengaturan.donasi'
import { Route as AdminPengaturanCountdownRouteImport } from './routes/admin.pengaturan.countdown'

const TwibbonRoute = TwibbonRouteImport.update({
  id: '/twibbon',
  path: '/twibbon',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SuksesRoute = SuksesRouteImport.update({
  id: '/sukses',
  path: '/sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const PendaftaranSuksesRoute = PendaftaranSuksesRouteImport.update({
  id: '/pendaftaran-sukses',
  path: '/pendaftaran-sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const PendaftaranRoute = PendaftaranRouteImport.update({
  id: '/pendaftaran',
  path: '/pendaftaran',
  getParentRoute: () => rootRouteImport,
} as any)
const EssayRoute = EssayRouteImport.update({
  id: '/essay',
  path: '/essay',
  getParentRoute: () => rootRouteImport,
} as any)
const DonasiRoute = DonasiRouteImport.update({
  id: '/donasi',
  path: '/donasi',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarMandiriRoute = DaftarMandiriRouteImport.update({
  id: '/daftar-mandiri',
  path: '/daftar-mandiri',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarGelombang2Route = DaftarGelombang2RouteImport.update({
  id: '/daftar-gelombang-2',
  path: '/daftar-gelombang-2',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarGelombang1Route = DaftarGelombang1RouteImport.update({
  id: '/daftar-gelombang-1',
  path: '/daftar-gelombang-1',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasRoute = BerkasRouteImport.update({
  id: '/berkas',
  path: '/berkas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaSetupRoute = AdminWaSetupRouteImport.update({
  id: '/admin/wa-setup',
  path: '/admin/wa-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesertaIndexRoute = AdminPesertaIndexRouteImport.update({
  id: '/admin/peserta/',
  path: '/admin/peserta/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanIndexRoute = AdminPengaturanIndexRouteImport.update({
  id: '/admin/pengaturan/',
  path: '/admin/pengaturan/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesertaSelfFundedRoute = AdminPesertaSelfFundedRouteImport.update({
  id: '/admin/peserta/self-funded',
  path: '/admin/peserta/self-funded',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesertaRegulerRoute = AdminPesertaRegulerRouteImport.update({
  id: '/admin/peserta/reguler',
  path: '/admin/peserta/reguler',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanTwibbonRoute = AdminPengaturanTwibbonRouteImport.update({
  id: '/admin/pengaturan/twibbon',
  path: '/admin/pengaturan/twibbon',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanPanduanRoute = AdminPengaturanPanduanRouteImport.update({
  id: '/admin/pengaturan/panduan',
  path: '/admin/pengaturan/panduan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanGelombangRoute =
  AdminPengaturanGelombangRouteImport.update({
    id: '/admin/pengaturan/gelombang',
    path: '/admin/pengaturan/gelombang',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPengaturanDonasiRoute = AdminPengaturanDonasiRouteImport.update({
  id: '/admin/pengaturan/donasi',
  path: '/admin/pengaturan/donasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanCountdownRoute =
  AdminPengaturanCountdownRouteImport.update({
    id: '/admin/pengaturan/countdown',
    path: '/admin/pengaturan/countdown',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/berkas': typeof BerkasRoute
  '/daftar': typeof DaftarRoute
  '/daftar-gelombang-1': typeof DaftarGelombang1Route
  '/daftar-gelombang-2': typeof DaftarGelombang2Route
  '/daftar-mandiri': typeof DaftarMandiriRoute
  '/donasi': typeof DonasiRoute
  '/essay': typeof EssayRoute
  '/pendaftaran': typeof PendaftaranRoute
  '/pendaftaran-sukses': typeof PendaftaranSuksesRoute
  '/sukses': typeof SuksesRoute
  '/tentang': typeof TentangRoute
  '/twibbon': typeof TwibbonRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/wa-setup': typeof AdminWaSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pengaturan/countdown': typeof AdminPengaturanCountdownRoute
  '/admin/pengaturan/donasi': typeof AdminPengaturanDonasiRoute
  '/admin/pengaturan/gelombang': typeof AdminPengaturanGelombangRoute
  '/admin/pengaturan/panduan': typeof AdminPengaturanPanduanRoute
  '/admin/pengaturan/twibbon': typeof AdminPengaturanTwibbonRoute
  '/admin/peserta/reguler': typeof AdminPesertaRegulerRoute
  '/admin/peserta/self-funded': typeof AdminPesertaSelfFundedRoute
  '/admin/pengaturan/': typeof AdminPengaturanIndexRoute
  '/admin/peserta/': typeof AdminPesertaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/berkas': typeof BerkasRoute
  '/daftar': typeof DaftarRoute
  '/daftar-gelombang-1': typeof DaftarGelombang1Route
  '/daftar-gelombang-2': typeof DaftarGelombang2Route
  '/daftar-mandiri': typeof DaftarMandiriRoute
  '/donasi': typeof DonasiRoute
  '/essay': typeof EssayRoute
  '/pendaftaran': typeof PendaftaranRoute
  '/pendaftaran-sukses': typeof PendaftaranSuksesRoute
  '/sukses': typeof SuksesRoute
  '/tentang': typeof TentangRoute
  '/twibbon': typeof TwibbonRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/wa-setup': typeof AdminWaSetupRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pengaturan/countdown': typeof AdminPengaturanCountdownRoute
  '/admin/pengaturan/donasi': typeof AdminPengaturanDonasiRoute
  '/admin/pengaturan/gelombang': typeof AdminPengaturanGelombangRoute
  '/admin/pengaturan/panduan': typeof AdminPengaturanPanduanRoute
  '/admin/pengaturan/twibbon': typeof AdminPengaturanTwibbonRoute
  '/admin/peserta/reguler': typeof AdminPesertaRegulerRoute
  '/admin/peserta/self-funded': typeof AdminPesertaSelfFundedRoute
  '/admin/pengaturan': typeof AdminPengaturanIndexRoute
  '/admin/peserta': typeof AdminPesertaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/berkas': typeof BerkasRoute
  '/daftar': typeof DaftarRoute
  '/daftar-gelombang-1': typeof DaftarGelombang1Route
  '/daftar-gelombang-2': typeof DaftarGelombang2Route
  '/daftar-mandiri': typeof DaftarMandiriRoute
  '/donasi': typeof DonasiRoute
  '/essay': typeof EssayRoute
  '/pendaftaran': typeof PendaftaranRoute
  '/pendaftaran-sukses': typeof PendaftaranSuksesRoute
  '/sukses': typeof SuksesRoute
  '/tentang': typeof TentangRoute
  '/twibbon': typeof TwibbonRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/wa-setup': typeof AdminWaSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pengaturan/countdown': typeof AdminPengaturanCountdownRoute
  '/admin/pengaturan/donasi': typeof AdminPengaturanDonasiRoute
  '/admin/pengaturan/gelombang': typeof AdminPengaturanGelombangRoute
  '/admin/pengaturan/panduan': typeof AdminPengaturanPanduanRoute
  '/admin/pengaturan/twibbon': typeof AdminPengaturanTwibbonRoute
  '/admin/peserta/reguler': typeof AdminPesertaRegulerRoute
  '/admin/peserta/self-funded': typeof AdminPesertaSelfFundedRoute
  '/admin/pengaturan/': typeof AdminPengaturanIndexRoute
  '/admin/peserta/': typeof AdminPesertaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/berkas'
    | '/daftar'
    | '/daftar-gelombang-1'
    | '/daftar-gelombang-2'
    | '/daftar-mandiri'
    | '/donasi'
    | '/essay'
    | '/pendaftaran'
    | '/pendaftaran-sukses'
    | '/sukses'
    | '/tentang'
    | '/twibbon'
    | '/admin/login'
    | '/admin/wa-setup'
    | '/admin/'
    | '/admin/pengaturan/countdown'
    | '/admin/pengaturan/donasi'
    | '/admin/pengaturan/gelombang'
    | '/admin/pengaturan/panduan'
    | '/admin/pengaturan/twibbon'
    | '/admin/peserta/reguler'
    | '/admin/peserta/self-funded'
    | '/admin/pengaturan/'
    | '/admin/peserta/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/berkas'
    | '/daftar'
    | '/daftar-gelombang-1'
    | '/daftar-gelombang-2'
    | '/daftar-mandiri'
    | '/donasi'
    | '/essay'
    | '/pendaftaran'
    | '/pendaftaran-sukses'
    | '/sukses'
    | '/tentang'
    | '/twibbon'
    | '/admin/login'
    | '/admin/wa-setup'
    | '/admin'
    | '/admin/pengaturan/countdown'
    | '/admin/pengaturan/donasi'
    | '/admin/pengaturan/gelombang'
    | '/admin/pengaturan/panduan'
    | '/admin/pengaturan/twibbon'
    | '/admin/peserta/reguler'
    | '/admin/peserta/self-funded'
    | '/admin/pengaturan'
    | '/admin/peserta'
  id:
    | '__root__'
    | '/'
    | '/berkas'
    | '/daftar'
    | '/daftar-gelombang-1'
    | '/daftar-gelombang-2'
    | '/daftar-mandiri'
    | '/donasi'
    | '/essay'
    | '/pendaftaran'
    | '/pendaftaran-sukses'
    | '/sukses'
    | '/tentang'
    | '/twibbon'
    | '/admin/login'
    | '/admin/wa-setup'
    | '/admin/'
    | '/admin/pengaturan/countdown'
    | '/admin/pengaturan/donasi'
    | '/admin/pengaturan/gelombang'
    | '/admin/pengaturan/panduan'
    | '/admin/pengaturan/twibbon'
    | '/admin/peserta/reguler'
    | '/admin/peserta/self-funded'
    | '/admin/pengaturan/'
    | '/admin/peserta/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BerkasRoute: typeof BerkasRoute
  DaftarRoute: typeof DaftarRoute
  DaftarGelombang1Route: typeof DaftarGelombang1Route
  DaftarGelombang2Route: typeof DaftarGelombang2Route
  DaftarMandiriRoute: typeof DaftarMandiriRoute
  DonasiRoute: typeof DonasiRoute
  EssayRoute: typeof EssayRoute
  PendaftaranRoute: typeof PendaftaranRoute
  PendaftaranSuksesRoute: typeof PendaftaranSuksesRoute
  SuksesRoute: typeof SuksesRoute
  TentangRoute: typeof TentangRoute
  TwibbonRoute: typeof TwibbonRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminWaSetupRoute: typeof AdminWaSetupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPengaturanCountdownRoute: typeof AdminPengaturanCountdownRoute
  AdminPengaturanDonasiRoute: typeof AdminPengaturanDonasiRoute
  AdminPengaturanGelombangRoute: typeof AdminPengaturanGelombangRoute
  AdminPengaturanPanduanRoute: typeof AdminPengaturanPanduanRoute
  AdminPengaturanTwibbonRoute: typeof AdminPengaturanTwibbonRoute
  AdminPesertaRegulerRoute: typeof AdminPesertaRegulerRoute
  AdminPesertaSelfFundedRoute: typeof AdminPesertaSelfFundedRoute
  AdminPengaturanIndexRoute: typeof AdminPengaturanIndexRoute
  AdminPesertaIndexRoute: typeof AdminPesertaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/twibbon': {
      id: '/twibbon'
      path: '/twibbon'
      fullPath: '/twibbon'
      preLoaderRoute: typeof TwibbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sukses': {
      id: '/sukses'
      path: '/sukses'
      fullPath: '/sukses'
      preLoaderRoute: typeof SuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendaftaran-sukses': {
      id: '/pendaftaran-sukses'
      path: '/pendaftaran-sukses'
      fullPath: '/pendaftaran-sukses'
      preLoaderRoute: typeof PendaftaranSuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendaftaran': {
      id: '/pendaftaran'
      path: '/pendaftaran'
      fullPath: '/pendaftaran'
      preLoaderRoute: typeof PendaftaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay': {
      id: '/essay'
      path: '/essay'
      fullPath: '/essay'
      preLoaderRoute: typeof EssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donasi': {
      id: '/donasi'
      path: '/donasi'
      fullPath: '/donasi'
      preLoaderRoute: typeof DonasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-mandiri': {
      id: '/daftar-mandiri'
      path: '/daftar-mandiri'
      fullPath: '/daftar-mandiri'
      preLoaderRoute: typeof DaftarMandiriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-gelombang-2': {
      id: '/daftar-gelombang-2'
      path: '/daftar-gelombang-2'
      fullPath: '/daftar-gelombang-2'
      preLoaderRoute: typeof DaftarGelombang2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-gelombang-1': {
      id: '/daftar-gelombang-1'
      path: '/daftar-gelombang-1'
      fullPath: '/daftar-gelombang-1'
      preLoaderRoute: typeof DaftarGelombang1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas': {
      id: '/berkas'
      path: '/berkas'
      fullPath: '/berkas'
      preLoaderRoute: typeof BerkasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wa-setup': {
      id: '/admin/wa-setup'
      path: '/admin/wa-setup'
      fullPath: '/admin/wa-setup'
      preLoaderRoute: typeof AdminWaSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peserta/': {
      id: '/admin/peserta/'
      path: '/admin/peserta'
      fullPath: '/admin/peserta/'
      preLoaderRoute: typeof AdminPesertaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/': {
      id: '/admin/pengaturan/'
      path: '/admin/pengaturan'
      fullPath: '/admin/pengaturan/'
      preLoaderRoute: typeof AdminPengaturanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peserta/self-funded': {
      id: '/admin/peserta/self-funded'
      path: '/admin/peserta/self-funded'
      fullPath: '/admin/peserta/self-funded'
      preLoaderRoute: typeof AdminPesertaSelfFundedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peserta/reguler': {
      id: '/admin/peserta/reguler'
      path: '/admin/peserta/reguler'
      fullPath: '/admin/peserta/reguler'
      preLoaderRoute: typeof AdminPesertaRegulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/twibbon': {
      id: '/admin/pengaturan/twibbon'
      path: '/admin/pengaturan/twibbon'
      fullPath: '/admin/pengaturan/twibbon'
      preLoaderRoute: typeof AdminPengaturanTwibbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/panduan': {
      id: '/admin/pengaturan/panduan'
      path: '/admin/pengaturan/panduan'
      fullPath: '/admin/pengaturan/panduan'
      preLoaderRoute: typeof AdminPengaturanPanduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/gelombang': {
      id: '/admin/pengaturan/gelombang'
      path: '/admin/pengaturan/gelombang'
      fullPath: '/admin/pengaturan/gelombang'
      preLoaderRoute: typeof AdminPengaturanGelombangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/donasi': {
      id: '/admin/pengaturan/donasi'
      path: '/admin/pengaturan/donasi'
      fullPath: '/admin/pengaturan/donasi'
      preLoaderRoute: typeof AdminPengaturanDonasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/countdown': {
      id: '/admin/pengaturan/countdown'
      path: '/admin/pengaturan/countdown'
      fullPath: '/admin/pengaturan/countdown'
      preLoaderRoute: typeof AdminPengaturanCountdownRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BerkasRoute: BerkasRoute,
  DaftarRoute: DaftarRoute,
  DaftarGelombang1Route: DaftarGelombang1Route,
  DaftarGelombang2Route: DaftarGelombang2Route,
  DaftarMandiriRoute: DaftarMandiriRoute,
  DonasiRoute: DonasiRoute,
  EssayRoute: EssayRoute,
  PendaftaranRoute: PendaftaranRoute,
  PendaftaranSuksesRoute: PendaftaranSuksesRoute,
  SuksesRoute: SuksesRoute,
  TentangRoute: TentangRoute,
  TwibbonRoute: TwibbonRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminWaSetupRoute: AdminWaSetupRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPengaturanCountdownRoute: AdminPengaturanCountdownRoute,
  AdminPengaturanDonasiRoute: AdminPengaturanDonasiRoute,
  AdminPengaturanGelombangRoute: AdminPengaturanGelombangRoute,
  AdminPengaturanPanduanRoute: AdminPengaturanPanduanRoute,
  AdminPengaturanTwibbonRoute: AdminPengaturanTwibbonRoute,
  AdminPesertaRegulerRoute: AdminPesertaRegulerRoute,
  AdminPesertaSelfFundedRoute: AdminPesertaSelfFundedRoute,
  AdminPengaturanIndexRoute: AdminPengaturanIndexRoute,
  AdminPesertaIndexRoute: AdminPesertaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
