/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TwibbonRouteImport } from './routes/twibbon'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SuksesRouteImport } from './routes/sukses'
import { Route as PendaftaranSuksesRouteImport } from './routes/pendaftaran-sukses'
import { Route as PendaftaranRouteImport } from './routes/pendaftaran'
import { Route as PanduanRouteImport } from './routes/panduan'
import { Route as KontribusiSuksesRouteImport } from './routes/kontribusi-sukses'
import { Route as KontribusiRouteImport } from './routes/kontribusi'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EssaySuksesRouteImport } from './routes/essay-sukses'
import { Route as EssayRouteImport } from './routes/essay'
import { Route as DaftarMandiriRouteImport } from './routes/daftar-mandiri'
import { Route as DaftarGelombang2RouteImport } from './routes/daftar-gelombang-2'
import { Route as DaftarGelombang1RouteImport } from './routes/daftar-gelombang-1'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as CekTahapanRouteImport } from './routes/cek-tahapan'
import { Route as CekHasilRouteImport } from './routes/cek-hasil'
import { Route as BerkasRouteImport } from './routes/berkas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminWaSetupRouteImport } from './routes/admin.wa-setup'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPesertaIndexRouteImport } from './routes/admin.peserta.index'
import { Route as AdminPengaturanIndexRouteImport } from './routes/admin.pengaturan.index'
import { Route as AdminPesertaTahapanRouteImport } from './routes/admin.peserta.tahapan'
import { Route as AdminPesertaSelfFundedRouteImport } from './routes/admin.peserta.self-funded'
import { Route as AdminPesertaRegulerRouteImport } from './routes/admin.peserta.reguler'
import { Route as AdminPesertaKontribusiRouteImport } from './routes/admin.peserta.kontribusi'
import { Route as AdminPesertaEssayApiRouteImport } from './routes/admin.peserta.essay-api'
import { Route as AdminPesertaEssayRouteImport } from './routes/admin.peserta.essay'
import { Route as AdminPengaturanWaQuickReplyRouteImport } from './routes/admin.pengaturan.wa-quick-reply'
import { Route as AdminPengaturanWaChannelRouteImport } from './routes/admin.pengaturan.wa-channel'
import { Route as AdminPengaturanTwibbonRouteImport } from './routes/admin.pengaturan.twibbon'
import { Route as AdminPengaturanTimelineRouteImport } from './routes/admin.pengaturan.timeline'
import { Route as AdminPengaturanPanduanRouteImport } from './routes/admin.pengaturan.panduan'
import { Route as AdminPengaturanMediaRouteImport } from './routes/admin.pengaturan.media'
import { Route as AdminPengaturanHasilSeleksiRouteImport } from './routes/admin.pengaturan.hasil-seleksi'
import { Route as AdminPengaturanGelombangRouteImport } from './routes/admin.pengaturan.gelombang'
import { Route as AdminPengaturanFaqRouteImport } from './routes/admin.pengaturan.faq'
import { Route as AdminPengaturanEmailRouteImport } from './routes/admin.pengaturan.email'
import { Route as AdminPengaturanDonasiRouteImport } from './routes/admin.pengaturan.donasi'
import { Route as AdminPengaturanDokumenSelfFundedRouteImport } from './routes/admin.pengaturan.dokumen-self-funded'
import { Route as AdminPengaturanCountdownRouteImport } from './routes/admin.pengaturan.countdown'
import { Route as AdminPengaturanApresiasiRouteImport } from './routes/admin.pengaturan.apresiasi'
import { Route as AdminPengaturanAiProviderRouteImport } from './routes/admin.pengaturan.ai-provider'
import { Route as AdminPengaturanAffiliateRouteImport } from './routes/admin.pengaturan.affiliate'
import { Route as AdminAlurTahapanSeleksiRouteImport } from './routes/admin.alur.tahapan-seleksi'
import { Route as AdminAlurFullyFundedRouteImport } from './routes/admin.alur.fully-funded'
import { Route as AdminPesertaSelfFundedIndexRouteImport } from './routes/admin.peserta.self-funded.index'
import { Route as AdminPesertaRegulerIndexRouteImport } from './routes/admin.peserta.reguler.index'
import { Route as AdminPesertaSelfFundedPendaftaranRouteImport } from './routes/admin.peserta.self-funded.pendaftaran'
import { Route as AdminPesertaRegulerPendaftaranRouteImport } from './routes/admin.peserta.reguler.pendaftaran'
import { Route as AdminPesertaRegulerBerkasRouteImport } from './routes/admin.peserta.reguler.berkas'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TwibbonRoute = TwibbonRouteImport.update({
  id: '/twibbon',
  path: '/twibbon',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SuksesRoute = SuksesRouteImport.update({
  id: '/sukses',
  path: '/sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const PendaftaranSuksesRoute = PendaftaranSuksesRouteImport.update({
  id: '/pendaftaran-sukses',
  path: '/pendaftaran-sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const PendaftaranRoute = PendaftaranRouteImport.update({
  id: '/pendaftaran',
  path: '/pendaftaran',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanRoute = PanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => rootRouteImport,
} as any)
const KontribusiSuksesRoute = KontribusiSuksesRouteImport.update({
  id: '/kontribusi-sukses',
  path: '/kontribusi-sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const KontribusiRoute = KontribusiRouteImport.update({
  id: '/kontribusi',
  path: '/kontribusi',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EssaySuksesRoute = EssaySuksesRouteImport.update({
  id: '/essay-sukses',
  path: '/essay-sukses',
  getParentRoute: () => rootRouteImport,
} as any)
const EssayRoute = EssayRouteImport.update({
  id: '/essay',
  path: '/essay',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarMandiriRoute = DaftarMandiriRouteImport.update({
  id: '/daftar-mandiri',
  path: '/daftar-mandiri',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarGelombang2Route = DaftarGelombang2RouteImport.update({
  id: '/daftar-gelombang-2',
  path: '/daftar-gelombang-2',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarGelombang1Route = DaftarGelombang1RouteImport.update({
  id: '/daftar-gelombang-1',
  path: '/daftar-gelombang-1',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const CekTahapanRoute = CekTahapanRouteImport.update({
  id: '/cek-tahapan',
  path: '/cek-tahapan',
  getParentRoute: () => rootRouteImport,
} as any)
const CekHasilRoute = CekHasilRouteImport.update({
  id: '/cek-hasil',
  path: '/cek-hasil',
  getParentRoute: () => rootRouteImport,
} as any)
const BerkasRoute = BerkasRouteImport.update({
  id: '/berkas',
  path: '/berkas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaSetupRoute = AdminWaSetupRouteImport.update({
  id: '/admin/wa-setup',
  path: '/admin/wa-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesertaIndexRoute = AdminPesertaIndexRouteImport.update({
  id: '/admin/peserta/',
  path: '/admin/peserta/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanIndexRoute = AdminPengaturanIndexRouteImport.update({
  id: '/admin/pengaturan/',
  path: '/admin/pengaturan/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesertaTahapanRoute = AdminPesertaTahapanRouteImport.update({
  id: '/admin/peserta/tahapan',
  path: '/admin/peserta/tahapan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesertaSelfFundedRoute = AdminPesertaSelfFundedRouteImport.update({
  id: '/admin/peserta/self-funded',
  path: '/admin/peserta/self-funded',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesertaRegulerRoute = AdminPesertaRegulerRouteImport.update({
  id: '/admin/peserta/reguler',
  path: '/admin/peserta/reguler',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesertaKontribusiRoute = AdminPesertaKontribusiRouteImport.update({
  id: '/admin/peserta/kontribusi',
  path: '/admin/peserta/kontribusi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesertaEssayApiRoute = AdminPesertaEssayApiRouteImport.update({
  id: '/admin/peserta/essay-api',
  path: '/admin/peserta/essay-api',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesertaEssayRoute = AdminPesertaEssayRouteImport.update({
  id: '/admin/peserta/essay',
  path: '/admin/peserta/essay',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanWaQuickReplyRoute =
  AdminPengaturanWaQuickReplyRouteImport.update({
    id: '/admin/pengaturan/wa-quick-reply',
    path: '/admin/pengaturan/wa-quick-reply',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPengaturanWaChannelRoute =
  AdminPengaturanWaChannelRouteImport.update({
    id: '/admin/pengaturan/wa-channel',
    path: '/admin/pengaturan/wa-channel',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPengaturanTwibbonRoute = AdminPengaturanTwibbonRouteImport.update({
  id: '/admin/pengaturan/twibbon',
  path: '/admin/pengaturan/twibbon',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanTimelineRoute = AdminPengaturanTimelineRouteImport.update({
  id: '/admin/pengaturan/timeline',
  path: '/admin/pengaturan/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanPanduanRoute = AdminPengaturanPanduanRouteImport.update({
  id: '/admin/pengaturan/panduan',
  path: '/admin/pengaturan/panduan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanMediaRoute = AdminPengaturanMediaRouteImport.update({
  id: '/admin/pengaturan/media',
  path: '/admin/pengaturan/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanHasilSeleksiRoute =
  AdminPengaturanHasilSeleksiRouteImport.update({
    id: '/admin/pengaturan/hasil-seleksi',
    path: '/admin/pengaturan/hasil-seleksi',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPengaturanGelombangRoute =
  AdminPengaturanGelombangRouteImport.update({
    id: '/admin/pengaturan/gelombang',
    path: '/admin/pengaturan/gelombang',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPengaturanFaqRoute = AdminPengaturanFaqRouteImport.update({
  id: '/admin/pengaturan/faq',
  path: '/admin/pengaturan/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanEmailRoute = AdminPengaturanEmailRouteImport.update({
  id: '/admin/pengaturan/email',
  path: '/admin/pengaturan/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanDonasiRoute = AdminPengaturanDonasiRouteImport.update({
  id: '/admin/pengaturan/donasi',
  path: '/admin/pengaturan/donasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanDokumenSelfFundedRoute =
  AdminPengaturanDokumenSelfFundedRouteImport.update({
    id: '/admin/pengaturan/dokumen-self-funded',
    path: '/admin/pengaturan/dokumen-self-funded',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPengaturanCountdownRoute =
  AdminPengaturanCountdownRouteImport.update({
    id: '/admin/pengaturan/countdown',
    path: '/admin/pengaturan/countdown',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPengaturanApresiasiRoute =
  AdminPengaturanApresiasiRouteImport.update({
    id: '/admin/pengaturan/apresiasi',
    path: '/admin/pengaturan/apresiasi',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPengaturanAiProviderRoute =
  AdminPengaturanAiProviderRouteImport.update({
    id: '/admin/pengaturan/ai-provider',
    path: '/admin/pengaturan/ai-provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPengaturanAffiliateRoute =
  AdminPengaturanAffiliateRouteImport.update({
    id: '/admin/pengaturan/affiliate',
    path: '/admin/pengaturan/affiliate',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAlurTahapanSeleksiRoute = AdminAlurTahapanSeleksiRouteImport.update({
  id: '/admin/alur/tahapan-seleksi',
  path: '/admin/alur/tahapan-seleksi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlurFullyFundedRoute = AdminAlurFullyFundedRouteImport.update({
  id: '/admin/alur/fully-funded',
  path: '/admin/alur/fully-funded',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPesertaSelfFundedIndexRoute =
  AdminPesertaSelfFundedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminPesertaSelfFundedRoute,
  } as any)
const AdminPesertaRegulerIndexRoute =
  AdminPesertaRegulerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminPesertaRegulerRoute,
  } as any)
const AdminPesertaSelfFundedPendaftaranRoute =
  AdminPesertaSelfFundedPendaftaranRouteImport.update({
    id: '/pendaftaran',
    path: '/pendaftaran',
    getParentRoute: () => AdminPesertaSelfFundedRoute,
  } as any)
const AdminPesertaRegulerPendaftaranRoute =
  AdminPesertaRegulerPendaftaranRouteImport.update({
    id: '/pendaftaran',
    path: '/pendaftaran',
    getParentRoute: () => AdminPesertaRegulerRoute,
  } as any)
const AdminPesertaRegulerBerkasRoute =
  AdminPesertaRegulerBerkasRouteImport.update({
    id: '/berkas',
    path: '/berkas',
    getParentRoute: () => AdminPesertaRegulerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/berkas': typeof BerkasRoute
  '/cek-hasil': typeof CekHasilRoute
  '/cek-tahapan': typeof CekTahapanRoute
  '/daftar': typeof DaftarRoute
  '/daftar-gelombang-1': typeof DaftarGelombang1Route
  '/daftar-gelombang-2': typeof DaftarGelombang2Route
  '/daftar-mandiri': typeof DaftarMandiriRoute
  '/essay': typeof EssayRoute
  '/essay-sukses': typeof EssaySuksesRoute
  '/faq': typeof FaqRoute
  '/kontribusi': typeof KontribusiRoute
  '/kontribusi-sukses': typeof KontribusiSuksesRoute
  '/panduan': typeof PanduanRoute
  '/pendaftaran': typeof PendaftaranRoute
  '/pendaftaran-sukses': typeof PendaftaranSuksesRoute
  '/sukses': typeof SuksesRoute
  '/tentang': typeof TentangRoute
  '/twibbon': typeof TwibbonRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/wa-setup': typeof AdminWaSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/alur/fully-funded': typeof AdminAlurFullyFundedRoute
  '/admin/alur/tahapan-seleksi': typeof AdminAlurTahapanSeleksiRoute
  '/admin/pengaturan/affiliate': typeof AdminPengaturanAffiliateRoute
  '/admin/pengaturan/ai-provider': typeof AdminPengaturanAiProviderRoute
  '/admin/pengaturan/apresiasi': typeof AdminPengaturanApresiasiRoute
  '/admin/pengaturan/countdown': typeof AdminPengaturanCountdownRoute
  '/admin/pengaturan/dokumen-self-funded': typeof AdminPengaturanDokumenSelfFundedRoute
  '/admin/pengaturan/donasi': typeof AdminPengaturanDonasiRoute
  '/admin/pengaturan/email': typeof AdminPengaturanEmailRoute
  '/admin/pengaturan/faq': typeof AdminPengaturanFaqRoute
  '/admin/pengaturan/gelombang': typeof AdminPengaturanGelombangRoute
  '/admin/pengaturan/hasil-seleksi': typeof AdminPengaturanHasilSeleksiRoute
  '/admin/pengaturan/media': typeof AdminPengaturanMediaRoute
  '/admin/pengaturan/panduan': typeof AdminPengaturanPanduanRoute
  '/admin/pengaturan/timeline': typeof AdminPengaturanTimelineRoute
  '/admin/pengaturan/twibbon': typeof AdminPengaturanTwibbonRoute
  '/admin/pengaturan/wa-channel': typeof AdminPengaturanWaChannelRoute
  '/admin/pengaturan/wa-quick-reply': typeof AdminPengaturanWaQuickReplyRoute
  '/admin/peserta/essay': typeof AdminPesertaEssayRoute
  '/admin/peserta/essay-api': typeof AdminPesertaEssayApiRoute
  '/admin/peserta/kontribusi': typeof AdminPesertaKontribusiRoute
  '/admin/peserta/reguler': typeof AdminPesertaRegulerRouteWithChildren
  '/admin/peserta/self-funded': typeof AdminPesertaSelfFundedRouteWithChildren
  '/admin/peserta/tahapan': typeof AdminPesertaTahapanRoute
  '/admin/pengaturan/': typeof AdminPengaturanIndexRoute
  '/admin/peserta/': typeof AdminPesertaIndexRoute
  '/admin/peserta/reguler/berkas': typeof AdminPesertaRegulerBerkasRoute
  '/admin/peserta/reguler/pendaftaran': typeof AdminPesertaRegulerPendaftaranRoute
  '/admin/peserta/self-funded/pendaftaran': typeof AdminPesertaSelfFundedPendaftaranRoute
  '/admin/peserta/reguler/': typeof AdminPesertaRegulerIndexRoute
  '/admin/peserta/self-funded/': typeof AdminPesertaSelfFundedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/berkas': typeof BerkasRoute
  '/cek-hasil': typeof CekHasilRoute
  '/cek-tahapan': typeof CekTahapanRoute
  '/daftar': typeof DaftarRoute
  '/daftar-gelombang-1': typeof DaftarGelombang1Route
  '/daftar-gelombang-2': typeof DaftarGelombang2Route
  '/daftar-mandiri': typeof DaftarMandiriRoute
  '/essay': typeof EssayRoute
  '/essay-sukses': typeof EssaySuksesRoute
  '/faq': typeof FaqRoute
  '/kontribusi': typeof KontribusiRoute
  '/kontribusi-sukses': typeof KontribusiSuksesRoute
  '/panduan': typeof PanduanRoute
  '/pendaftaran': typeof PendaftaranRoute
  '/pendaftaran-sukses': typeof PendaftaranSuksesRoute
  '/sukses': typeof SuksesRoute
  '/tentang': typeof TentangRoute
  '/twibbon': typeof TwibbonRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/wa-setup': typeof AdminWaSetupRoute
  '/admin': typeof AdminIndexRoute
  '/admin/alur/fully-funded': typeof AdminAlurFullyFundedRoute
  '/admin/alur/tahapan-seleksi': typeof AdminAlurTahapanSeleksiRoute
  '/admin/pengaturan/affiliate': typeof AdminPengaturanAffiliateRoute
  '/admin/pengaturan/ai-provider': typeof AdminPengaturanAiProviderRoute
  '/admin/pengaturan/apresiasi': typeof AdminPengaturanApresiasiRoute
  '/admin/pengaturan/countdown': typeof AdminPengaturanCountdownRoute
  '/admin/pengaturan/dokumen-self-funded': typeof AdminPengaturanDokumenSelfFundedRoute
  '/admin/pengaturan/donasi': typeof AdminPengaturanDonasiRoute
  '/admin/pengaturan/email': typeof AdminPengaturanEmailRoute
  '/admin/pengaturan/faq': typeof AdminPengaturanFaqRoute
  '/admin/pengaturan/gelombang': typeof AdminPengaturanGelombangRoute
  '/admin/pengaturan/hasil-seleksi': typeof AdminPengaturanHasilSeleksiRoute
  '/admin/pengaturan/media': typeof AdminPengaturanMediaRoute
  '/admin/pengaturan/panduan': typeof AdminPengaturanPanduanRoute
  '/admin/pengaturan/timeline': typeof AdminPengaturanTimelineRoute
  '/admin/pengaturan/twibbon': typeof AdminPengaturanTwibbonRoute
  '/admin/pengaturan/wa-channel': typeof AdminPengaturanWaChannelRoute
  '/admin/pengaturan/wa-quick-reply': typeof AdminPengaturanWaQuickReplyRoute
  '/admin/peserta/essay': typeof AdminPesertaEssayRoute
  '/admin/peserta/essay-api': typeof AdminPesertaEssayApiRoute
  '/admin/peserta/kontribusi': typeof AdminPesertaKontribusiRoute
  '/admin/peserta/tahapan': typeof AdminPesertaTahapanRoute
  '/admin/pengaturan': typeof AdminPengaturanIndexRoute
  '/admin/peserta': typeof AdminPesertaIndexRoute
  '/admin/peserta/reguler/berkas': typeof AdminPesertaRegulerBerkasRoute
  '/admin/peserta/reguler/pendaftaran': typeof AdminPesertaRegulerPendaftaranRoute
  '/admin/peserta/self-funded/pendaftaran': typeof AdminPesertaSelfFundedPendaftaranRoute
  '/admin/peserta/reguler': typeof AdminPesertaRegulerIndexRoute
  '/admin/peserta/self-funded': typeof AdminPesertaSelfFundedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/berkas': typeof BerkasRoute
  '/cek-hasil': typeof CekHasilRoute
  '/cek-tahapan': typeof CekTahapanRoute
  '/daftar': typeof DaftarRoute
  '/daftar-gelombang-1': typeof DaftarGelombang1Route
  '/daftar-gelombang-2': typeof DaftarGelombang2Route
  '/daftar-mandiri': typeof DaftarMandiriRoute
  '/essay': typeof EssayRoute
  '/essay-sukses': typeof EssaySuksesRoute
  '/faq': typeof FaqRoute
  '/kontribusi': typeof KontribusiRoute
  '/kontribusi-sukses': typeof KontribusiSuksesRoute
  '/panduan': typeof PanduanRoute
  '/pendaftaran': typeof PendaftaranRoute
  '/pendaftaran-sukses': typeof PendaftaranSuksesRoute
  '/sukses': typeof SuksesRoute
  '/tentang': typeof TentangRoute
  '/twibbon': typeof TwibbonRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/wa-setup': typeof AdminWaSetupRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/alur/fully-funded': typeof AdminAlurFullyFundedRoute
  '/admin/alur/tahapan-seleksi': typeof AdminAlurTahapanSeleksiRoute
  '/admin/pengaturan/affiliate': typeof AdminPengaturanAffiliateRoute
  '/admin/pengaturan/ai-provider': typeof AdminPengaturanAiProviderRoute
  '/admin/pengaturan/apresiasi': typeof AdminPengaturanApresiasiRoute
  '/admin/pengaturan/countdown': typeof AdminPengaturanCountdownRoute
  '/admin/pengaturan/dokumen-self-funded': typeof AdminPengaturanDokumenSelfFundedRoute
  '/admin/pengaturan/donasi': typeof AdminPengaturanDonasiRoute
  '/admin/pengaturan/email': typeof AdminPengaturanEmailRoute
  '/admin/pengaturan/faq': typeof AdminPengaturanFaqRoute
  '/admin/pengaturan/gelombang': typeof AdminPengaturanGelombangRoute
  '/admin/pengaturan/hasil-seleksi': typeof AdminPengaturanHasilSeleksiRoute
  '/admin/pengaturan/media': typeof AdminPengaturanMediaRoute
  '/admin/pengaturan/panduan': typeof AdminPengaturanPanduanRoute
  '/admin/pengaturan/timeline': typeof AdminPengaturanTimelineRoute
  '/admin/pengaturan/twibbon': typeof AdminPengaturanTwibbonRoute
  '/admin/pengaturan/wa-channel': typeof AdminPengaturanWaChannelRoute
  '/admin/pengaturan/wa-quick-reply': typeof AdminPengaturanWaQuickReplyRoute
  '/admin/peserta/essay': typeof AdminPesertaEssayRoute
  '/admin/peserta/essay-api': typeof AdminPesertaEssayApiRoute
  '/admin/peserta/kontribusi': typeof AdminPesertaKontribusiRoute
  '/admin/peserta/reguler': typeof AdminPesertaRegulerRouteWithChildren
  '/admin/peserta/self-funded': typeof AdminPesertaSelfFundedRouteWithChildren
  '/admin/peserta/tahapan': typeof AdminPesertaTahapanRoute
  '/admin/pengaturan/': typeof AdminPengaturanIndexRoute
  '/admin/peserta/': typeof AdminPesertaIndexRoute
  '/admin/peserta/reguler/berkas': typeof AdminPesertaRegulerBerkasRoute
  '/admin/peserta/reguler/pendaftaran': typeof AdminPesertaRegulerPendaftaranRoute
  '/admin/peserta/self-funded/pendaftaran': typeof AdminPesertaSelfFundedPendaftaranRoute
  '/admin/peserta/reguler/': typeof AdminPesertaRegulerIndexRoute
  '/admin/peserta/self-funded/': typeof AdminPesertaSelfFundedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/berkas'
    | '/cek-hasil'
    | '/cek-tahapan'
    | '/daftar'
    | '/daftar-gelombang-1'
    | '/daftar-gelombang-2'
    | '/daftar-mandiri'
    | '/essay'
    | '/essay-sukses'
    | '/faq'
    | '/kontribusi'
    | '/kontribusi-sukses'
    | '/panduan'
    | '/pendaftaran'
    | '/pendaftaran-sukses'
    | '/sukses'
    | '/tentang'
    | '/twibbon'
    | '/unsubscribe'
    | '/admin/login'
    | '/admin/wa-setup'
    | '/admin/'
    | '/admin/alur/fully-funded'
    | '/admin/alur/tahapan-seleksi'
    | '/admin/pengaturan/affiliate'
    | '/admin/pengaturan/ai-provider'
    | '/admin/pengaturan/apresiasi'
    | '/admin/pengaturan/countdown'
    | '/admin/pengaturan/dokumen-self-funded'
    | '/admin/pengaturan/donasi'
    | '/admin/pengaturan/email'
    | '/admin/pengaturan/faq'
    | '/admin/pengaturan/gelombang'
    | '/admin/pengaturan/hasil-seleksi'
    | '/admin/pengaturan/media'
    | '/admin/pengaturan/panduan'
    | '/admin/pengaturan/timeline'
    | '/admin/pengaturan/twibbon'
    | '/admin/pengaturan/wa-channel'
    | '/admin/pengaturan/wa-quick-reply'
    | '/admin/peserta/essay'
    | '/admin/peserta/essay-api'
    | '/admin/peserta/kontribusi'
    | '/admin/peserta/reguler'
    | '/admin/peserta/self-funded'
    | '/admin/peserta/tahapan'
    | '/admin/pengaturan/'
    | '/admin/peserta/'
    | '/admin/peserta/reguler/berkas'
    | '/admin/peserta/reguler/pendaftaran'
    | '/admin/peserta/self-funded/pendaftaran'
    | '/admin/peserta/reguler/'
    | '/admin/peserta/self-funded/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/berkas'
    | '/cek-hasil'
    | '/cek-tahapan'
    | '/daftar'
    | '/daftar-gelombang-1'
    | '/daftar-gelombang-2'
    | '/daftar-mandiri'
    | '/essay'
    | '/essay-sukses'
    | '/faq'
    | '/kontribusi'
    | '/kontribusi-sukses'
    | '/panduan'
    | '/pendaftaran'
    | '/pendaftaran-sukses'
    | '/sukses'
    | '/tentang'
    | '/twibbon'
    | '/unsubscribe'
    | '/admin/login'
    | '/admin/wa-setup'
    | '/admin'
    | '/admin/alur/fully-funded'
    | '/admin/alur/tahapan-seleksi'
    | '/admin/pengaturan/affiliate'
    | '/admin/pengaturan/ai-provider'
    | '/admin/pengaturan/apresiasi'
    | '/admin/pengaturan/countdown'
    | '/admin/pengaturan/dokumen-self-funded'
    | '/admin/pengaturan/donasi'
    | '/admin/pengaturan/email'
    | '/admin/pengaturan/faq'
    | '/admin/pengaturan/gelombang'
    | '/admin/pengaturan/hasil-seleksi'
    | '/admin/pengaturan/media'
    | '/admin/pengaturan/panduan'
    | '/admin/pengaturan/timeline'
    | '/admin/pengaturan/twibbon'
    | '/admin/pengaturan/wa-channel'
    | '/admin/pengaturan/wa-quick-reply'
    | '/admin/peserta/essay'
    | '/admin/peserta/essay-api'
    | '/admin/peserta/kontribusi'
    | '/admin/peserta/tahapan'
    | '/admin/pengaturan'
    | '/admin/peserta'
    | '/admin/peserta/reguler/berkas'
    | '/admin/peserta/reguler/pendaftaran'
    | '/admin/peserta/self-funded/pendaftaran'
    | '/admin/peserta/reguler'
    | '/admin/peserta/self-funded'
  id:
    | '__root__'
    | '/'
    | '/berkas'
    | '/cek-hasil'
    | '/cek-tahapan'
    | '/daftar'
    | '/daftar-gelombang-1'
    | '/daftar-gelombang-2'
    | '/daftar-mandiri'
    | '/essay'
    | '/essay-sukses'
    | '/faq'
    | '/kontribusi'
    | '/kontribusi-sukses'
    | '/panduan'
    | '/pendaftaran'
    | '/pendaftaran-sukses'
    | '/sukses'
    | '/tentang'
    | '/twibbon'
    | '/unsubscribe'
    | '/admin/login'
    | '/admin/wa-setup'
    | '/admin/'
    | '/admin/alur/fully-funded'
    | '/admin/alur/tahapan-seleksi'
    | '/admin/pengaturan/affiliate'
    | '/admin/pengaturan/ai-provider'
    | '/admin/pengaturan/apresiasi'
    | '/admin/pengaturan/countdown'
    | '/admin/pengaturan/dokumen-self-funded'
    | '/admin/pengaturan/donasi'
    | '/admin/pengaturan/email'
    | '/admin/pengaturan/faq'
    | '/admin/pengaturan/gelombang'
    | '/admin/pengaturan/hasil-seleksi'
    | '/admin/pengaturan/media'
    | '/admin/pengaturan/panduan'
    | '/admin/pengaturan/timeline'
    | '/admin/pengaturan/twibbon'
    | '/admin/pengaturan/wa-channel'
    | '/admin/pengaturan/wa-quick-reply'
    | '/admin/peserta/essay'
    | '/admin/peserta/essay-api'
    | '/admin/peserta/kontribusi'
    | '/admin/peserta/reguler'
    | '/admin/peserta/self-funded'
    | '/admin/peserta/tahapan'
    | '/admin/pengaturan/'
    | '/admin/peserta/'
    | '/admin/peserta/reguler/berkas'
    | '/admin/peserta/reguler/pendaftaran'
    | '/admin/peserta/self-funded/pendaftaran'
    | '/admin/peserta/reguler/'
    | '/admin/peserta/self-funded/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BerkasRoute: typeof BerkasRoute
  CekHasilRoute: typeof CekHasilRoute
  CekTahapanRoute: typeof CekTahapanRoute
  DaftarRoute: typeof DaftarRoute
  DaftarGelombang1Route: typeof DaftarGelombang1Route
  DaftarGelombang2Route: typeof DaftarGelombang2Route
  DaftarMandiriRoute: typeof DaftarMandiriRoute
  EssayRoute: typeof EssayRoute
  EssaySuksesRoute: typeof EssaySuksesRoute
  FaqRoute: typeof FaqRoute
  KontribusiRoute: typeof KontribusiRoute
  KontribusiSuksesRoute: typeof KontribusiSuksesRoute
  PanduanRoute: typeof PanduanRoute
  PendaftaranRoute: typeof PendaftaranRoute
  PendaftaranSuksesRoute: typeof PendaftaranSuksesRoute
  SuksesRoute: typeof SuksesRoute
  TentangRoute: typeof TentangRoute
  TwibbonRoute: typeof TwibbonRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminWaSetupRoute: typeof AdminWaSetupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlurFullyFundedRoute: typeof AdminAlurFullyFundedRoute
  AdminAlurTahapanSeleksiRoute: typeof AdminAlurTahapanSeleksiRoute
  AdminPengaturanAffiliateRoute: typeof AdminPengaturanAffiliateRoute
  AdminPengaturanAiProviderRoute: typeof AdminPengaturanAiProviderRoute
  AdminPengaturanApresiasiRoute: typeof AdminPengaturanApresiasiRoute
  AdminPengaturanCountdownRoute: typeof AdminPengaturanCountdownRoute
  AdminPengaturanDokumenSelfFundedRoute: typeof AdminPengaturanDokumenSelfFundedRoute
  AdminPengaturanDonasiRoute: typeof AdminPengaturanDonasiRoute
  AdminPengaturanEmailRoute: typeof AdminPengaturanEmailRoute
  AdminPengaturanFaqRoute: typeof AdminPengaturanFaqRoute
  AdminPengaturanGelombangRoute: typeof AdminPengaturanGelombangRoute
  AdminPengaturanHasilSeleksiRoute: typeof AdminPengaturanHasilSeleksiRoute
  AdminPengaturanMediaRoute: typeof AdminPengaturanMediaRoute
  AdminPengaturanPanduanRoute: typeof AdminPengaturanPanduanRoute
  AdminPengaturanTimelineRoute: typeof AdminPengaturanTimelineRoute
  AdminPengaturanTwibbonRoute: typeof AdminPengaturanTwibbonRoute
  AdminPengaturanWaChannelRoute: typeof AdminPengaturanWaChannelRoute
  AdminPengaturanWaQuickReplyRoute: typeof AdminPengaturanWaQuickReplyRoute
  AdminPesertaEssayRoute: typeof AdminPesertaEssayRoute
  AdminPesertaEssayApiRoute: typeof AdminPesertaEssayApiRoute
  AdminPesertaKontribusiRoute: typeof AdminPesertaKontribusiRoute
  AdminPesertaRegulerRoute: typeof AdminPesertaRegulerRouteWithChildren
  AdminPesertaSelfFundedRoute: typeof AdminPesertaSelfFundedRouteWithChildren
  AdminPesertaTahapanRoute: typeof AdminPesertaTahapanRoute
  AdminPengaturanIndexRoute: typeof AdminPengaturanIndexRoute
  AdminPesertaIndexRoute: typeof AdminPesertaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twibbon': {
      id: '/twibbon'
      path: '/twibbon'
      fullPath: '/twibbon'
      preLoaderRoute: typeof TwibbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sukses': {
      id: '/sukses'
      path: '/sukses'
      fullPath: '/sukses'
      preLoaderRoute: typeof SuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendaftaran-sukses': {
      id: '/pendaftaran-sukses'
      path: '/pendaftaran-sukses'
      fullPath: '/pendaftaran-sukses'
      preLoaderRoute: typeof PendaftaranSuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendaftaran': {
      id: '/pendaftaran'
      path: '/pendaftaran'
      fullPath: '/pendaftaran'
      preLoaderRoute: typeof PendaftaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan': {
      id: '/panduan'
      path: '/panduan'
      fullPath: '/panduan'
      preLoaderRoute: typeof PanduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontribusi-sukses': {
      id: '/kontribusi-sukses'
      path: '/kontribusi-sukses'
      fullPath: '/kontribusi-sukses'
      preLoaderRoute: typeof KontribusiSuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontribusi': {
      id: '/kontribusi'
      path: '/kontribusi'
      fullPath: '/kontribusi'
      preLoaderRoute: typeof KontribusiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay-sukses': {
      id: '/essay-sukses'
      path: '/essay-sukses'
      fullPath: '/essay-sukses'
      preLoaderRoute: typeof EssaySuksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essay': {
      id: '/essay'
      path: '/essay'
      fullPath: '/essay'
      preLoaderRoute: typeof EssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-mandiri': {
      id: '/daftar-mandiri'
      path: '/daftar-mandiri'
      fullPath: '/daftar-mandiri'
      preLoaderRoute: typeof DaftarMandiriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-gelombang-2': {
      id: '/daftar-gelombang-2'
      path: '/daftar-gelombang-2'
      fullPath: '/daftar-gelombang-2'
      preLoaderRoute: typeof DaftarGelombang2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-gelombang-1': {
      id: '/daftar-gelombang-1'
      path: '/daftar-gelombang-1'
      fullPath: '/daftar-gelombang-1'
      preLoaderRoute: typeof DaftarGelombang1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-tahapan': {
      id: '/cek-tahapan'
      path: '/cek-tahapan'
      fullPath: '/cek-tahapan'
      preLoaderRoute: typeof CekTahapanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-hasil': {
      id: '/cek-hasil'
      path: '/cek-hasil'
      fullPath: '/cek-hasil'
      preLoaderRoute: typeof CekHasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berkas': {
      id: '/berkas'
      path: '/berkas'
      fullPath: '/berkas'
      preLoaderRoute: typeof BerkasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wa-setup': {
      id: '/admin/wa-setup'
      path: '/admin/wa-setup'
      fullPath: '/admin/wa-setup'
      preLoaderRoute: typeof AdminWaSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peserta/': {
      id: '/admin/peserta/'
      path: '/admin/peserta'
      fullPath: '/admin/peserta/'
      preLoaderRoute: typeof AdminPesertaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/': {
      id: '/admin/pengaturan/'
      path: '/admin/pengaturan'
      fullPath: '/admin/pengaturan/'
      preLoaderRoute: typeof AdminPengaturanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peserta/tahapan': {
      id: '/admin/peserta/tahapan'
      path: '/admin/peserta/tahapan'
      fullPath: '/admin/peserta/tahapan'
      preLoaderRoute: typeof AdminPesertaTahapanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peserta/self-funded': {
      id: '/admin/peserta/self-funded'
      path: '/admin/peserta/self-funded'
      fullPath: '/admin/peserta/self-funded'
      preLoaderRoute: typeof AdminPesertaSelfFundedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peserta/reguler': {
      id: '/admin/peserta/reguler'
      path: '/admin/peserta/reguler'
      fullPath: '/admin/peserta/reguler'
      preLoaderRoute: typeof AdminPesertaRegulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peserta/kontribusi': {
      id: '/admin/peserta/kontribusi'
      path: '/admin/peserta/kontribusi'
      fullPath: '/admin/peserta/kontribusi'
      preLoaderRoute: typeof AdminPesertaKontribusiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peserta/essay-api': {
      id: '/admin/peserta/essay-api'
      path: '/admin/peserta/essay-api'
      fullPath: '/admin/peserta/essay-api'
      preLoaderRoute: typeof AdminPesertaEssayApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peserta/essay': {
      id: '/admin/peserta/essay'
      path: '/admin/peserta/essay'
      fullPath: '/admin/peserta/essay'
      preLoaderRoute: typeof AdminPesertaEssayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/wa-quick-reply': {
      id: '/admin/pengaturan/wa-quick-reply'
      path: '/admin/pengaturan/wa-quick-reply'
      fullPath: '/admin/pengaturan/wa-quick-reply'
      preLoaderRoute: typeof AdminPengaturanWaQuickReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/wa-channel': {
      id: '/admin/pengaturan/wa-channel'
      path: '/admin/pengaturan/wa-channel'
      fullPath: '/admin/pengaturan/wa-channel'
      preLoaderRoute: typeof AdminPengaturanWaChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/twibbon': {
      id: '/admin/pengaturan/twibbon'
      path: '/admin/pengaturan/twibbon'
      fullPath: '/admin/pengaturan/twibbon'
      preLoaderRoute: typeof AdminPengaturanTwibbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/timeline': {
      id: '/admin/pengaturan/timeline'
      path: '/admin/pengaturan/timeline'
      fullPath: '/admin/pengaturan/timeline'
      preLoaderRoute: typeof AdminPengaturanTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/panduan': {
      id: '/admin/pengaturan/panduan'
      path: '/admin/pengaturan/panduan'
      fullPath: '/admin/pengaturan/panduan'
      preLoaderRoute: typeof AdminPengaturanPanduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/media': {
      id: '/admin/pengaturan/media'
      path: '/admin/pengaturan/media'
      fullPath: '/admin/pengaturan/media'
      preLoaderRoute: typeof AdminPengaturanMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/hasil-seleksi': {
      id: '/admin/pengaturan/hasil-seleksi'
      path: '/admin/pengaturan/hasil-seleksi'
      fullPath: '/admin/pengaturan/hasil-seleksi'
      preLoaderRoute: typeof AdminPengaturanHasilSeleksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/gelombang': {
      id: '/admin/pengaturan/gelombang'
      path: '/admin/pengaturan/gelombang'
      fullPath: '/admin/pengaturan/gelombang'
      preLoaderRoute: typeof AdminPengaturanGelombangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/faq': {
      id: '/admin/pengaturan/faq'
      path: '/admin/pengaturan/faq'
      fullPath: '/admin/pengaturan/faq'
      preLoaderRoute: typeof AdminPengaturanFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/email': {
      id: '/admin/pengaturan/email'
      path: '/admin/pengaturan/email'
      fullPath: '/admin/pengaturan/email'
      preLoaderRoute: typeof AdminPengaturanEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/donasi': {
      id: '/admin/pengaturan/donasi'
      path: '/admin/pengaturan/donasi'
      fullPath: '/admin/pengaturan/donasi'
      preLoaderRoute: typeof AdminPengaturanDonasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/dokumen-self-funded': {
      id: '/admin/pengaturan/dokumen-self-funded'
      path: '/admin/pengaturan/dokumen-self-funded'
      fullPath: '/admin/pengaturan/dokumen-self-funded'
      preLoaderRoute: typeof AdminPengaturanDokumenSelfFundedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/countdown': {
      id: '/admin/pengaturan/countdown'
      path: '/admin/pengaturan/countdown'
      fullPath: '/admin/pengaturan/countdown'
      preLoaderRoute: typeof AdminPengaturanCountdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/apresiasi': {
      id: '/admin/pengaturan/apresiasi'
      path: '/admin/pengaturan/apresiasi'
      fullPath: '/admin/pengaturan/apresiasi'
      preLoaderRoute: typeof AdminPengaturanApresiasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/ai-provider': {
      id: '/admin/pengaturan/ai-provider'
      path: '/admin/pengaturan/ai-provider'
      fullPath: '/admin/pengaturan/ai-provider'
      preLoaderRoute: typeof AdminPengaturanAiProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan/affiliate': {
      id: '/admin/pengaturan/affiliate'
      path: '/admin/pengaturan/affiliate'
      fullPath: '/admin/pengaturan/affiliate'
      preLoaderRoute: typeof AdminPengaturanAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alur/tahapan-seleksi': {
      id: '/admin/alur/tahapan-seleksi'
      path: '/admin/alur/tahapan-seleksi'
      fullPath: '/admin/alur/tahapan-seleksi'
      preLoaderRoute: typeof AdminAlurTahapanSeleksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alur/fully-funded': {
      id: '/admin/alur/fully-funded'
      path: '/admin/alur/fully-funded'
      fullPath: '/admin/alur/fully-funded'
      preLoaderRoute: typeof AdminAlurFullyFundedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/peserta/self-funded/': {
      id: '/admin/peserta/self-funded/'
      path: '/'
      fullPath: '/admin/peserta/self-funded/'
      preLoaderRoute: typeof AdminPesertaSelfFundedIndexRouteImport
      parentRoute: typeof AdminPesertaSelfFundedRoute
    }
    '/admin/peserta/reguler/': {
      id: '/admin/peserta/reguler/'
      path: '/'
      fullPath: '/admin/peserta/reguler/'
      preLoaderRoute: typeof AdminPesertaRegulerIndexRouteImport
      parentRoute: typeof AdminPesertaRegulerRoute
    }
    '/admin/peserta/self-funded/pendaftaran': {
      id: '/admin/peserta/self-funded/pendaftaran'
      path: '/pendaftaran'
      fullPath: '/admin/peserta/self-funded/pendaftaran'
      preLoaderRoute: typeof AdminPesertaSelfFundedPendaftaranRouteImport
      parentRoute: typeof AdminPesertaSelfFundedRoute
    }
    '/admin/peserta/reguler/pendaftaran': {
      id: '/admin/peserta/reguler/pendaftaran'
      path: '/pendaftaran'
      fullPath: '/admin/peserta/reguler/pendaftaran'
      preLoaderRoute: typeof AdminPesertaRegulerPendaftaranRouteImport
      parentRoute: typeof AdminPesertaRegulerRoute
    }
    '/admin/peserta/reguler/berkas': {
      id: '/admin/peserta/reguler/berkas'
      path: '/berkas'
      fullPath: '/admin/peserta/reguler/berkas'
      preLoaderRoute: typeof AdminPesertaRegulerBerkasRouteImport
      parentRoute: typeof AdminPesertaRegulerRoute
    }
  }
}

interface AdminPesertaRegulerRouteChildren {
  AdminPesertaRegulerBerkasRoute: typeof AdminPesertaRegulerBerkasRoute
  AdminPesertaRegulerPendaftaranRoute: typeof AdminPesertaRegulerPendaftaranRoute
  AdminPesertaRegulerIndexRoute: typeof AdminPesertaRegulerIndexRoute
}

const AdminPesertaRegulerRouteChildren: AdminPesertaRegulerRouteChildren = {
  AdminPesertaRegulerBerkasRoute: AdminPesertaRegulerBerkasRoute,
  AdminPesertaRegulerPendaftaranRoute: AdminPesertaRegulerPendaftaranRoute,
  AdminPesertaRegulerIndexRoute: AdminPesertaRegulerIndexRoute,
}

const AdminPesertaRegulerRouteWithChildren =
  AdminPesertaRegulerRoute._addFileChildren(AdminPesertaRegulerRouteChildren)

interface AdminPesertaSelfFundedRouteChildren {
  AdminPesertaSelfFundedPendaftaranRoute: typeof AdminPesertaSelfFundedPendaftaranRoute
  AdminPesertaSelfFundedIndexRoute: typeof AdminPesertaSelfFundedIndexRoute
}

const AdminPesertaSelfFundedRouteChildren: AdminPesertaSelfFundedRouteChildren =
  {
    AdminPesertaSelfFundedPendaftaranRoute:
      AdminPesertaSelfFundedPendaftaranRoute,
    AdminPesertaSelfFundedIndexRoute: AdminPesertaSelfFundedIndexRoute,
  }

const AdminPesertaSelfFundedRouteWithChildren =
  AdminPesertaSelfFundedRoute._addFileChildren(
    AdminPesertaSelfFundedRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BerkasRoute: BerkasRoute,
  CekHasilRoute: CekHasilRoute,
  CekTahapanRoute: CekTahapanRoute,
  DaftarRoute: DaftarRoute,
  DaftarGelombang1Route: DaftarGelombang1Route,
  DaftarGelombang2Route: DaftarGelombang2Route,
  DaftarMandiriRoute: DaftarMandiriRoute,
  EssayRoute: EssayRoute,
  EssaySuksesRoute: EssaySuksesRoute,
  FaqRoute: FaqRoute,
  KontribusiRoute: KontribusiRoute,
  KontribusiSuksesRoute: KontribusiSuksesRoute,
  PanduanRoute: PanduanRoute,
  PendaftaranRoute: PendaftaranRoute,
  PendaftaranSuksesRoute: PendaftaranSuksesRoute,
  SuksesRoute: SuksesRoute,
  TentangRoute: TentangRoute,
  TwibbonRoute: TwibbonRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminWaSetupRoute: AdminWaSetupRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAlurFullyFundedRoute: AdminAlurFullyFundedRoute,
  AdminAlurTahapanSeleksiRoute: AdminAlurTahapanSeleksiRoute,
  AdminPengaturanAffiliateRoute: AdminPengaturanAffiliateRoute,
  AdminPengaturanAiProviderRoute: AdminPengaturanAiProviderRoute,
  AdminPengaturanApresiasiRoute: AdminPengaturanApresiasiRoute,
  AdminPengaturanCountdownRoute: AdminPengaturanCountdownRoute,
  AdminPengaturanDokumenSelfFundedRoute: AdminPengaturanDokumenSelfFundedRoute,
  AdminPengaturanDonasiRoute: AdminPengaturanDonasiRoute,
  AdminPengaturanEmailRoute: AdminPengaturanEmailRoute,
  AdminPengaturanFaqRoute: AdminPengaturanFaqRoute,
  AdminPengaturanGelombangRoute: AdminPengaturanGelombangRoute,
  AdminPengaturanHasilSeleksiRoute: AdminPengaturanHasilSeleksiRoute,
  AdminPengaturanMediaRoute: AdminPengaturanMediaRoute,
  AdminPengaturanPanduanRoute: AdminPengaturanPanduanRoute,
  AdminPengaturanTimelineRoute: AdminPengaturanTimelineRoute,
  AdminPengaturanTwibbonRoute: AdminPengaturanTwibbonRoute,
  AdminPengaturanWaChannelRoute: AdminPengaturanWaChannelRoute,
  AdminPengaturanWaQuickReplyRoute: AdminPengaturanWaQuickReplyRoute,
  AdminPesertaEssayRoute: AdminPesertaEssayRoute,
  AdminPesertaEssayApiRoute: AdminPesertaEssayApiRoute,
  AdminPesertaKontribusiRoute: AdminPesertaKontribusiRoute,
  AdminPesertaRegulerRoute: AdminPesertaRegulerRouteWithChildren,
  AdminPesertaSelfFundedRoute: AdminPesertaSelfFundedRouteWithChildren,
  AdminPesertaTahapanRoute: AdminPesertaTahapanRoute,
  AdminPengaturanIndexRoute: AdminPengaturanIndexRoute,
  AdminPesertaIndexRoute: AdminPesertaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
